### ISSUE TITLE
Detailed event information

### ISSUE THREAD

**Issue by rowan01g** [rowan01g/love_running#4]
**User Story**
As a potential event attendee, I want to view detailed information about each event so that I can decide if I want to attend.

**Acceptance Criteria**

- [ ] Each event listing links to a detailed event page.
- [ ] The detailed event page includes the event name, date, time, location, and a detailed description.
- [ ] The page also includes any relevant images or flyers.

**Tasks** 

- [ ] Each event listing links to a detailed event page.
- [ ] The detailed event page includes the event name, date, time, location, and a detailed description.
- [ ] The page also includes any relevant images or flyers.
